name: powerlog
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  sqflite:
  path_provider:
  intl:
  flutter_staggered_grid_view:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.8.2+3
  firebase_auth: 0.6.6
  firebase_database: 1.0.5


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/PowerAppIcon.png
   - assets/Sps.gif
   - assets/facebook.png
   - drive-steering-wheel.jpg
   - line.png
   - assets/images/dev.png
   - assets/images/hs.png
   - assets/images/mk.png
   - assets/images/na.png
   - assets/images/aa.png
   - assets/images/rs.png
   - assets/images/rb.jpg
   - assets/images/barackobama.png
   - assets/images/charliechaplin.png
   - assets/images/batman.png
   - assets/images/dalailama.png
   - assets/images/mahatmagandhi.png
   - assets/images/mickjagger.png
   - assets/images/nativeman.png
   - assets/images/nikolatesla.png
   - assets/images/robot.png
   - assets/images/captain.png
   - assets/pimage/div.png
   - assets/pimage/dvm1.jpg
   - assets/pimage/1.png
   - assets/pimage/2.png
   - assets/pimage/3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          style: normal
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Sans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Italic.ttf
          style: italic
        - asset: fonts/ProductSans-Bold.ttf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
